In [1]:
import pandas as pd
import os

In [2]:
dataset = 'nicla_digits'

In [3]:
folder = './source'
target = 'digit'

In [11]:
result = pd.DataFrame()
for file in sorted(os.listdir(folder)):
  class_ = int((file.split(sep='.')[0]))
  df = pd.read_csv(os.path.join(folder, file), skip_blank_lines=True)
  df[target] = class_
  result = pd.concat((result, df), axis=0, ignore_index=True)

In [12]:
result.drop(columns=['gyro_X', 'gyro_Y', 'gyro_Z'], inplace=True)

In [13]:
result

        acc_X  acc_Y  acc_Z  digit
0         599   1166   4514      0
1         556   1216   4423      0
2         404   1316   4214      0
3         204   1464   3932      0
4          77   1528   3624      0
...       ...    ...    ...    ...
399995   1608   1618   5385      9
399996   1592   1448   5384      9
399997   1566   1137   5321      9
399998   1474    792   5244      9
399999   1370    726   5249      9

[400000 rows x 4 columns]

In [14]:
result[target].value_counts()

0    40000
1    40000
2    40000
3    40000
4    40000
5    40000
6    40000
7    40000
8    40000
9    40000
Name: digit, dtype: int64

In [15]:
result.to_csv(f'{dataset}.csv', index=False)